export type WorkItem = {
  slug: string;
  title: string;
  eyebrow: string;
  promise?: string;
  status?: string;
  proofCopy?: string;
  problem: string;
  built: string;
  whyItMatters: string;
  proves: string;
  href?: string;
  external?: string;
  homepageLinks?: Array<{
    label: string;
    href: string;
  }>;
  homepageImage?: string;
  image?: string;
  productPage?: {
    tabLabel: string;
    category: string;
    image: {
      src: string;
      alt: string;
      width: number;
      height: number;
    };
    secondaryImages?: Array<{
      src: string;
      alt: string;
      width: number;
      height: number;
    }>;
    sections: Array<{
      label: string;
      paragraphs?: string[];
      stats?: Array<{
        accent?: string;
        text: string;
      }>;
      features?: Array<{
        title: string;
        text: string;
      }>;
      bullets?: string[];
      closing?: string[];
    }>;
    sideSections?: Array<{
      label: string;
      paragraphs?: string[];
      closing?: string[];
    }>;
    sideQuote?: string;
    testimonials?: Array<{
      quote: string;
      attribution: string;
    }>;
    featuredIn?: Array<{
      label: string;
      href: string;
    }>;
    ctas?: Array<{
      label: string;
      href: string;
      external?: boolean;
    }>;
  };
};

export const workItems: WorkItem[] = [
  {
    slug: "calm-authority",
    title: "Calm Authority",
    eyebrow: "Product / financial advice / authority systems",
    promise: "Your Own Expertise. At Scale.",
    status: "Live product",
    proofCopy:
      "Your Own Expertise. At Scale. Flagship product from Studio Baggio, turning adviser expertise into publish-ready authority content.",
    problem:
      "37,136 UK financial advisers are authorised, but fewer than 300 post consistently on LinkedIn.",
    built:
      "A live LinkedIn writing system that maps each adviser's voice, surfaces weekly angles and drafts posts from an idea, URL or article.",
    whyItMatters:
      "It turns private expertise into public proof while keeping the adviser in control: every post is reviewed, edited and published manually.",
    proves:
      "Studio Baggio can turn expert judgement, compliance constraints and a market visibility gap into a practical AI-enabled product.",
    external: "https://www.calmauthority.ai/",
    homepageLinks: [
      { label: "Find out more →", href: "/work" },
      { label: "Visit live site →", href: "https://www.calmauthority.ai" }
    ],
    homepageImage: "/assets/products/calm-authority-og-featured-16x9.png",
    image: "/assets/products/calm-authority.png",
    productPage: {
      tabLabel: "Calm Authority",
      category: "LinkedIn Thought Leadership Writing System",
      image: {
        src: "/assets/products/calm-authority-featured-in.png",
        alt: "Calm Authority brand proof graphic showing featured publications",
        width: 1672,
        height: 941
      },
      sections: [
        {
          label: "01 — The Problem",
          paragraphs: [
            "LinkedIn is the #1 platform for client conversions among advisers, yet of the 37,136 authorised financial advisers in the UK, fewer than 300 post consistently on LinkedIn. In a relationship business, that is a structural visibility gap.",
            "Clients trust adviser judgement in private, but prospects have no evidence the expertise your website claims actually exists. An\u00A0adviser sharing market insight, client-relevant commentary, and professional perspective starts building trust before the first meeting. Clients come in warm, not cold."
          ],
          stats: [
            {
              accent: "99%",
              text: "of UK financial advisers don't post consistently. Those who start now will capture market share. The ones who wait will miss the window."
            },
            {
              accent: "23%",
              text: "of Millennials and Gen Z wouldn't consider an adviser they can't find online."
            },
            {
              accent: "96%",
              text: "of prospective clients research professionals online before making contact."
            },
            {
              accent: "5-10x more reach",
              text: "is generated by personal posts compared with company page posts."
            }
          ],
          closing: [
            "Your best marketing asset is already on the payroll.",
            "Your advisers already interpret markets, simplify complexity, and build trust through conversation. The only thing missing is a system that makes that expertise visible beyond the meeting room."
          ]
        },
        {
          label: "02 — What is Calm Authority.",
          paragraphs: [
            "Calm Authority is a tone-of-voice writing system that maps how you write, researches what's relevant, and turns ideas into publish-ready LinkedIn drafts in your own voice.",
            "What makes it different from generic AI?"
          ],
          features: [
            {
              title: "Tone-of-Voice Mapping.",
              text: "Maps each adviser's writing style from a selection of samples: rhythm, phrasing and how they structure an argument. Every draft is constrained inside their voice profile."
            },
            {
              title: "Weekly Research Engine.",
              text: "Surfaces credible, audience-relevant angles every week."
            },
            {
              title: "Human-in-the-Loop.",
              text: "Nothing is auto-published. Advisers edit, approve and post themselves."
            },
            {
              title: "Built alongside Chartered Financial Planners.",
              text: "Informed by standards set by bodies including the Chartered Insurance Institute and FCA Consumer Duty expectations."
            }
          ],
          closing: [
            "Calm Authority operates inside firm policies, not around them.",
            "The system gets sharper with every edit. Designed for individuals and firms, with firm-level guardrails, adoption visibility for firm admins, and a structured 90-day rollout for advisory firms."
          ]
        }
      ],
      sideSections: [
        {
          label: "03 — Built By",
          paragraphs: [
            "Built in 2025 by Jayme Baggio, a content and systems strategist, with founding adviser Harry Sims, a Chartered Financial Planner with eleven years in financial services. Together they identified a structural visibility gap in the UK advice market, and built a system to close it."
          ]
        }
      ],
      testimonials: [
        {
          quote: "I've received 52 inbound leads in six months. Approx 60% from DMs, 40% from prospects reaching out to me.",
          attribution: "Harry Gallow, independent financial adviser"
        },
        {
          quote: "Since I started using Calm Authority, I've been booking around 2-3 meetings a week via LinkedIn. A great tool for building my personal brand.",
          attribution: "Nicola Podda DipPFS"
        },
        {
          quote: "£22,000 in new fees over six months, plus £18,000 in ongoing annual revenue from new clients. All from LinkedIn. No outreach.",
          attribution: "Harry Sims, independent financial adviser"
        },
        {
          quote: "+527% impressions in 28 days. One adviser, same audience: 48,000 to 301,314 impressions. Top single post reached 93,704. Viewers included EY, Deloitte, PwC, and HSBC.",
          attribution: "Harry Sims, independent financial adviser"
        }
      ],
      featuredIn: [
        {
          label: "FT Adviser",
          href: "https://www.ftadviser.com/content/32657fc7-9f35-4f05-bc93-8e8d33ece28d"
        },
        {
          label: "Professional Adviser",
          href: "https://www.professionaladviser.com/news/4527581/linkedin-ai-platform-financial-advisers-best-kept-secret"
        },
        {
          label: "Money Marketing",
          href: "https://www.moneymarketing.co.uk/features/at-the-helm-making-ai-more-than-an-efficiency-play/"
        }
      ],
      ctas: [{ label: "Visit live site →", href: "https://www.calmauthority.ai", external: true }]
    }
  },
  {
    slug: "business-tracker",
    title: "Business Tracker",
    eyebrow: "Lead intelligence / attribution / follow-up",
    promise: "Commercial intelligence",
    status: "Live system",
    proofCopy:
      "A market-specific prospecting system that captures interactions, qualifies named leads, adds AI rationale and produces a prioritised follow-up pipeline.",
    problem:
      "Smaller teams with valuable expertise often create visibility without knowing who is warming up, why they matter or what should happen next.",
    built:
      "The operating system captures every interaction across SEO, LinkedIn, lead magnets and email, makes it visible, and produces a named follow-up pipeline. Live AI search adds current public context to every lead so your team knows who is warming up, why they matter, and what to say next.",
    whyItMatters:
      "Built for businesses where high-value leads need careful nurturing: specialist advisers, founder-led firms and professional services teams with commercial touchpoints that currently sit apart.",
    proves:
      "Studio Baggio can connect visibility, market context and practical follow-up into one operating layer.",
    homepageLinks: [{ label: "Find out more →", href: "/work" }],
    homepageImage: "/assets/products/business-tracker-og.png",
    productPage: {
      tabLabel: "Business Tracker",
      category: "Commercial Intelligence",
      image: {
        src: "/assets/products/business-tracker-products-og.png",
        alt: "Business Tracker product graphic",
        width: 1672,
        height: 941
      },
      secondaryImages: [
        {
          src: "/business-tracker/hero/dashboard-hires.png",
          alt: "Business Tracker dashboard showing website analytics, SEO, email marketing, LinkedIn and lead qualification modules.",
          width: 1672,
          height: 941
        }
      ],
      sections: [
        {
          label: "What it does",
          paragraphs: [
            "Business Tracker is a commercial intelligence system. It captures every interaction across your channels, scores it against your criteria, and produces a ranked, named follow-up pipeline. Live AI search adds current public context to every lead so your team knows who is warming up, why they matter, and what to say next.",
            "It tracks what's happening, and what's performing, across:"
          ],
          features: [
            {
              title: "SEO + AI search —",
              text: "which articles convert, where you sit in search, AI search rationale"
            },
            {
              title: "LinkedIn —",
              text: "who's followed, commented and engaged; best-performing formats; what hooks work"
            },
            {
              title: "Lead magnets —",
              text: "who's interacted, engagement and lead quality"
            },
            {
              title: "Email —",
              text: "behavioural triggers, source attribution, campaign performance"
            }
          ],
          closing: [
            "It extends to any signal source bespoke to your business: events, podcasts, partnerships, whatever else drives commercial conversations in your market."
          ]
        },
        {
          label: "How it's different from a CRM",
          paragraphs: [
            "Unlike generic static CRMs or reporting dashboards, Business Tracker is purpose-built for lead capture and strategic insight in relationship-led industries.",
            "The new era lead tracker pulls public information about any person or company, then qualifies them against a rubric your business defines. Do they fit the ICP? Do they have budget? What did their CEO post on LinkedIn this week? Are they a standard commercial opportunity or a reputation play?",
            "The output becomes a rationale and a recommended angle for approach. It starts to look a lot less like a leads tracker and a lot more like a prospecting machine."
          ]
        }
      ],
      sideQuote:
        "Eyes and ears on who is searching for what you do, where they've engaged, who they are, and how they qualify against your bespoke criteria.",
      sideSections: [
        {
          label: "Built for",
          paragraphs: [
            "Businesses where high-value leads need careful nurturing: specialist advisers, founder-led firms and professional services teams with commercial touchpoints that currently sit apart."
          ]
        }
      ],
      ctas: []
    }
  },
  {
    slug: "last30days",
    title: "Last30Days",
    eyebrow: "Live signal intelligence / multi-source research",
    promise: "Live Signal Intelligence",
    status: "Live product",
    proofCopy:
      "Studio Baggio designed and built Last30Days, an AI research product that analyses recent conversations across social and community platforms and turns them into structured market intelligence. It has now been used by more than 250 individual and corporate users to research markets, competitors, customer questions and emerging opportunities.\n\nLast30Days scrapes Reddit. X. TikTok. Instagram. YouTube, Polymarket and the open web, pulling every conversation from the last thirty days. Ask any question: search a competitor, a trend, a product category, a new release. Get a structured, sourced report in under 60 seconds. Every claim cited.\n\nEvery business decision made without knowing what the market is saying right now is a guess dressed up as strategy. The best business intelligence is the kind your customers don't know they're producing. Last30Days gives you the market intelligence your competitors are paying £40,000 a year to access, in under 60 seconds.",
    problem:
      "Teams need to know what people are saying now, not what a stale report said months ago.",
    built:
      "This is where markets form their opinions. Where trends emerge before they reach the trade press. Where your competitors are being discussed, praised, or quietly abandoned.\n\nWhat used to take a research team, an agency brief, or a six-figure contract is now delivered in one search.",
    whyItMatters: "Before you launch, pivot or compete, know what the market is really saying right now.",
    proves:
      "Studio Baggio can build useful AI products that combine research, source discipline, synthesis and user-facing workflows.",
    href: "/last30days",
    external: "https://last30days.app",
    homepageLinks: [
      { label: "View product page →", href: "/last30days" },
      { label: "Visit live site →", href: "https://last30days.app" }
    ],
    homepageImage: "/assets/products/last30days-og.png",
    image: "/assets/products/last30days.png",
    productPage: {
      tabLabel: "Last30Days",
      category: "Live Signal Intelligence",
      image: {
        src: "/assets/products/last30days-products-og.png",
        alt: "Last30Days AI market intelligence product graphic",
        width: 1731,
        height: 909
      },
      sections: [
        {
          label: "What it is",
          paragraphs: [
            "Studio Baggio designed and built Last30Days, an AI research product that analyses recent conversations across social and community platforms and turns them into structured market intelligence. It has now been used by more than 250 individual and corporate users to research markets, competitors, customer questions and emerging opportunities.",
            "Last30Days scrapes Reddit. X. TikTok. Instagram. YouTube, Polymarket and the open web, pulling every conversation from the last thirty days. Ask any question: search a competitor, a trend, a product category, a new release. Get a structured, sourced report in under 60 seconds. Every claim cited.",
            "Every business decision made without knowing what the market is saying right now is a guess dressed up as strategy. The best business intelligence is the kind your customers don't know they're producing. Last30Days gives you the market intelligence your competitors are paying £40,000 a year to access, in under 60 seconds."
          ]
        },
        {
          label: "Useful for",
          bullets: [
            "Competitor research before a pitch, launch or positioning decision.",
            "Category research when you need to know what buyers are asking now.",
            "Trend research across Reddit, X, TikTok, Instagram, YouTube, Polymarket and the open web.",
            "Content angles, messaging gaps and market sentiment before you publish.",
            "Cited market intelligence that can be checked back to the original source."
          ]
        },
        {
          label: "Where markets form their opinions",
          paragraphs: [
            "This is where markets form their opinions. Where trends emerge before they reach the trade press. Where your competitors are being discussed, praised, or quietly abandoned."
          ]
        },
        {
          label: "What it replaces",
          paragraphs: [
            "What used to take a research team, an agency brief, or a six-figure contract is now delivered in one search.",
            "Before you launch, pivot or compete, know what the market is really saying right now."
          ],
        }
      ],
      ctas: [{ label: "Visit live site →", href: "https://last30days.app", external: true }]
    }
  },
  {
    slug: "fire-source",
    title: "Fire Source",
    eyebrow: "Commercial intelligence / cited web research",
    promise: "Market intelligence before the meeting.",
    status: "Placeholder case study",
    proofCopy:
      "Fire Source scans ~96% of the open web and answers your commercial questions in minutes. Stack follow-up questions to sharpen the picture and find the angle nobody else has.",
    problem:
      "Commercial teams need competitor moves, market shifts, buyer signals and pitch intelligence faster than manual research allows.",
    built:
      "Competitor moves, market shifts, who's spending in your sector, pricing changes, prospect, partner and hiring intelligence all in under three minutes. Cited, sourced & verified with prompts to turn the intel into pitches, emails, or strategy notes.",
    whyItMatters:
      "Use it to find prospects in your niche, identify who specifically meets your ICP, or research a potential partner or client before every meeting. Know who you're speaking with, what's important to them right now, why they might be buying, and whether they have the credentials to partner on the next deal.",
    proves:
      "Studio Baggio can build commercial intelligence products that preserve source discipline while accelerating decisions.",
    href: "/work",
    external: "https://fire-source.vercel.app",
    homepageLinks: [
      { label: "Find out more →", href: "/work" },
      { label: "Visit live site →", href: "https://fire-source.vercel.app" },
    ],
    homepageImage: "/assets/products/fire-source-og-use-this.png",
    image: "/assets/products/fire-source.png",
    productPage: {
      tabLabel: "Fire Source",
      category: "Commercial Intelligence",
      image: {
        src: "/assets/products/fire-source-og-use-this.png",
        alt: "Fire Source product graphic",
        width: 5760,
        height: 3240
      },
      sections: [
        {
          label: "Market Intelligence Before The Meeting",
          paragraphs: [
            "Fire Source scans ~96% of the open web and answers your commercial questions in three minutes. Stack follow-up questions to sharpen the picture and find the angle nobody else has. Competitor moves, market shifts, who's spending in your sector, pricing changes, prospect, partner and hiring intelligence all in under three minutes. Cited, sourced & verified, with prompts to turn the intel into pitches, emails or strategy notes."
          ]
        },
        {
          label: "What It Replaces",
          paragraphs: [
            "It replaces hours of manual research, briefings that go out of date, agency-commissioned reports, scattered Google searches and competitor benchmarking sessions you never had time to run properly."
          ]
        },
        {
          label: "Built for Firms That Move Fast",
          paragraphs: [
            "Fire Source is built for advisory & legal firms, consultancies and product teams who need commercial intelligence before the meeting, not after.",
            "Use it before any client meeting, pitch or partnership conversation to know:"
          ],
          bullets: [
            "Have they been on a podcast recently talking about something you offer?",
            "Have they got a reason to be buying from you?",
            "Do they have the credentials you're looking for to help partner on the next deal?"
          ]
        }
      ],
      ctas: [{ label: "Visit live site →", href: "https://fire-source.vercel.app", external: true }]
    }
  }
];
