export type WorkItem = {
  slug: string;
  title: string;
  eyebrow: string;
  promise?: string;
  status?: string;
  proofCopy?: string;
  problem: string;
  built: string;
  whyItMatters: string;
  proves: string;
  href?: string;
  external?: string;
  homepageLinks?: Array<{
    label: string;
    href: string;
  }>;
  homepageImage?: string;
  image?: string;
  productPage?: {
    tabLabel: string;
    category: string;
    image: {
      src: string;
      alt: string;
      width: number;
      height: number;
    };
    secondaryImages?: Array<{
      src: string;
      alt: string;
      width: number;
      height: number;
    }>;
    sections: Array<{
      label: string;
      paragraphs?: string[];
      stats?: Array<{
        accent?: string;
        text: string;
      }>;
      features?: Array<{
        title: string;
        text: string;
      }>;
      closing?: string[];
    }>;
    sideSections?: Array<{
      label: string;
      paragraphs?: string[];
      closing?: string[];
    }>;
    sideQuote?: string;
    testimonials?: Array<{
      quote: string;
      attribution: string;
    }>;
    featuredIn?: Array<{
      label: string;
      href: string;
    }>;
    ctas?: Array<{
      label: string;
      href: string;
      external?: boolean;
    }>;
  };
};

export const workItems: WorkItem[] = [
  {
    slug: "calm-authority",
    title: "Calm Authority",
    eyebrow: "Product / financial advice / authority systems",
    promise: "Your Own Expertise. At Scale.",
    status: "Live product",
    proofCopy:
      "‘ Your Own Expertise. At Scale ‘Flagship product from Studio Baggio- turning adviser expertise into publish-ready authority content.",
    problem:
      "37,136 UK financial advisers are authorised, but fewer than 300 post consistently on LinkedIn.",
    built:
      "A live LinkedIn writing system that maps each adviser's voice, surfaces weekly angles and drafts posts from an idea, URL or article.",
    whyItMatters:
      "It turns private expertise into public proof while keeping the adviser in control: every post is reviewed, edited and published manually.",
    proves:
      "Studio Baggio can turn expert judgement, compliance constraints and a market visibility gap into a practical AI-enabled product.",
    href: "/calm-authority",
    external: "https://www.calmauthority.ai/",
    homepageLinks: [
      { label: "See more →", href: "/calm-authority" },
      { label: "Visit live site →", href: "https://www.calmauthority.ai" }
    ],
    homepageImage: "/assets/products/calm-authority-og.png",
    image: "/assets/products/calm-authority.png",
    productPage: {
      tabLabel: "Calm Authority",
      category: "LinkedIn Thought Leadership Writing System",
      image: {
        src: "/assets/products/calm-authority-featured-in.png",
        alt: "Calm Authority brand proof graphic showing featured publications",
        width: 1672,
        height: 941
      },
      sections: [
        {
          label: "01 — The Problem",
          paragraphs: [
            "LinkedIn is the #1 platform for client conversions among advisers, yet of the 37,136 authorised financial advisers in the UK, fewer than 300 post consistently on LinkedIn. In a relationship business, that is a structural visibility gap.",
            "Clients trust adviser judgement in private — but prospects have no evidence the expertise your website claims actually exists. An\u00A0adviser sharing market insight, client-relevant commentary, and professional perspective starts building trust before the first meeting. Clients come in warm, not cold."
          ],
          stats: [
            {
              accent: "99%",
              text: "of UK financial advisers don't post consistently. Those who start now will capture market share. The ones who wait will miss the window."
            },
            {
              accent: "23%",
              text: "of Millennials and Gen Z wouldn't consider an adviser they can't find online."
            },
            {
              accent: "96%",
              text: "of prospective clients research professionals online before making contact."
            },
            {
              accent: "5-10x more reach",
              text: "is generated by personal posts compared with company page posts."
            }
          ],
          closing: [
            "Your best marketing asset is already on the payroll.",
            "Your advisers already interpret markets, simplify complexity, and build trust through conversation. The only thing missing is a system that makes that expertise visible beyond the meeting room."
          ]
        },
        {
          label: "02 — What is Calm Authority.",
          paragraphs: [
            "Calm Authority is a tone-of-voice writing system that maps how you write, researches what's relevant, and turns ideas into publish-ready LinkedIn drafts in your own voice.",
            "What makes it different from generic AI?"
          ],
          features: [
            {
              title: "Tone-of-Voice Mapping.",
              text: "Maps each adviser's writing style from a selection of samples — rhythm, phrasing and how they structure an argument. Every draft is constrained inside their voice profile."
            },
            {
              title: "Weekly Research Engine.",
              text: "Surfaces credible, audience-relevant angles every week."
            },
            {
              title: "Human-in-the-Loop.",
              text: "Nothing is auto-published. Advisers edit, approve and post themselves."
            },
            {
              title: "Built alongside Chartered Financial Planners.",
              text: "Informed by standards set by bodies including the Chartered Insurance Institute and FCA Consumer Duty expectations."
            }
          ],
          closing: [
            "Calm Authority operates inside firm policies, not around them.",
            "The system gets sharper with every edit. Designed for individuals and firms, with firm-level guardrails, adoption visibility for firm admins, and a structured 90-day rollout for advisory firms."
          ]
        }
      ],
      sideSections: [
        {
          label: "03 — Built By",
          paragraphs: [
            "Built in 2025 by Jayme Baggio, a content and systems strategist, with founding adviser Harry Sims, a Chartered Financial Planner with eleven years in financial services. Together they identified a structural visibility gap in the UK advice market — and built a system to close it."
          ]
        }
      ],
      testimonials: [
        {
          quote: "I've received 52 inbound leads in six months. Approx 60% from DMs, 40% from prospects reaching out to me.",
          attribution: "Harry Gallow, independent financial adviser"
        },
        {
          quote: "Since I started using Calm Authority, I've been booking around 2-3 meetings a week via LinkedIn. A great tool for building my personal brand.",
          attribution: "Nicola Podda DipPFS"
        },
        {
          quote: "£22,000 in new fees over six months, plus £18,000 in ongoing annual revenue from new clients. All from LinkedIn. No outreach.",
          attribution: "Harry Sims, independent financial adviser"
        },
        {
          quote: "+527% impressions in 28 days. One adviser, same audience: 48,000 to 301,314 impressions. Top single post reached 93,704. Viewers included EY, Deloitte, PwC, and HSBC.",
          attribution: "Harry Sims, independent financial adviser"
        }
      ],
      featuredIn: [
        {
          label: "Financial Times",
          href: "https://www.ftadviser.com/content/32657fc7-9f35-4f05-bc93-8e8d33ece28d"
        },
        {
          label: "Professional Adviser",
          href: "https://www.professionaladviser.com/news/4407649/could-linkedin-ai-platform-financial-advisers-best-kept-secret"
        },
        {
          label: "Money Marketing",
          href: "https://www.professionaladviser.com/news/4528430/risk-warnings-review-create-meaningful-shift-advice-communication"
        }
      ],
      ctas: [
        { label: "See more →", href: "/calm-authority" },
        { label: "Visit live site →", href: "https://www.calmauthority.ai", external: true }
      ]
    }
  },
  {
    slug: "business-tracker",
    title: "Business Tracker",
    eyebrow: "Lead intelligence / attribution / follow-up",
    promise: "Lead intelligence for warmer follow-up.",
    status: "Live system",
    proofCopy:
      "Turning engagement into named follow-up and lead intelligence.",
    problem:
      "Smaller expert-led teams often create visibility without knowing who is warming up, why they matter or what should happen next.",
    built:
      "A market-specific prospecting system that captures interactions, qualifies named leads, adds AI rationale and produces a prioritised follow-up pipeline.",
    whyItMatters:
      "It makes growth more feasible because teams can put time into conversations most likely to shift ROI.",
    proves:
      "Studio Baggio can connect visibility, market context and practical follow-up into one operating layer.",
    href: "/business-tracker",
    homepageLinks: [{ label: "See more →", href: "/business-tracker" }],
    homepageImage: "/assets/products/business-tracker-og.png",
    productPage: {
      tabLabel: "Business Tracker",
      category: "Commercial Intelligence",
      image: {
        src: "/assets/products/business-tracker-products-og.png",
        alt: "Business Tracker product graphic",
        width: 1672,
        height: 941
      },
      secondaryImages: [
        {
          src: "/business-tracker/hero/dashboard-hires.png",
          alt: "Business Tracker dashboard showing website analytics, SEO, email marketing, LinkedIn and lead qualification modules.",
          width: 1672,
          height: 941
        }
      ],
      sections: [
        {
          label: "What it does",
          paragraphs: [
            "Business Tracker is a commercial intelligence system. It captures every interaction across your channels, scores it against your criteria, and produces a ranked, named follow-up pipeline. Live AI search adds current public context to every lead so your team knows who is warming up, why they matter, and what to say next.",
            "It tracks what's happening — and what's performing — across:"
          ],
          features: [
            {
              title: "SEO + AI search —",
              text: "which articles convert, where you sit in search, AI search rationale"
            },
            {
              title: "LinkedIn —",
              text: "who's followed, commented and engaged; best-performing formats; what hooks work"
            },
            {
              title: "Lead magnets —",
              text: "who's interacted, engagement and lead quality"
            },
            {
              title: "Email —",
              text: "behavioural triggers, source attribution, campaign performance"
            }
          ],
          closing: [
            "It extends to any signal source bespoke to your business — events, podcasts, partnerships, whatever else drives commercial conversations in your market."
          ]
        },
        {
          label: "How it's different from a CRM",
          paragraphs: [
            "Unlike generic static CRMs or reporting dashboards, Business Tracker is purpose-built for lead capture and strategic insight in relationship-led industries.",
            "The new era lead tracker pulls public information about any person or company, then qualifies them against a rubric your business defines. Do they fit the ICP? Do they have budget? What did their CEO post on LinkedIn this week? Are they a standard commercial opportunity or a reputation play?",
            "The output becomes a rationale and a recommended angle for approach. It starts to look a lot less like a leads tracker and a lot more like a prospecting machine."
          ]
        }
      ],
      sideQuote:
        "Eyes and ears on who is searching for what you do, where they've engaged, who they are, and how they qualify against your bespoke criteria.",
      sideSections: [
        {
          label: "Built for",
          paragraphs: [
            "Expert-led firms where high-value leads need careful nurturing — specialist advisers, founder-led firms, professional services, and trust-based businesses with touchpoints that currently sit apart."
          ]
        }
      ],
      ctas: [{ label: "See more →", href: "/business-tracker" }]
    }
  },
  {
    slug: "last30days",
    title: "Last30Days",
    eyebrow: "Live signal intelligence / multi-source research",
    promise: "What the market is saying right now.",
    status: "Placeholder case study",
    proofCopy:
      "Pulls the last 30 days worth of discussion and sentiment from Reddit. X. TikTok. Instagram. YouTube (inc comments and transcripts). The open web- Where markets form real opinions. Where trends emerge before the press catches up. Where your competitors are being discussed, praised, or quietly abandoned. Ask any question - Last30Days outputs a fully sourced report in under sixty seconds - every claim cited. Before you launch, pivot, or compete - know what the market is really saying right now.",
    problem:
      "Teams need to know what people are saying now, not what a stale report said months ago.",
    built:
      "A reporting system that pulls recent discussion and sentiment from Reddit, X, TikTok, Instagram, YouTube and the open web, then turns it into a sourced market report.",
    whyItMatters:
      "It turns scattered current signals into structured intelligence that can support content, market mapping and commercial decisions.",
    proves:
      "Studio Baggio can build useful AI products that combine research, source discipline, synthesis and user-facing workflows.",
    href: "/last30days",
    external: "https://last30days.app",
    homepageLinks: [{ label: "Visit live site →", href: "https://last30days.app" }],
    homepageImage: "/assets/products/last30days-og.png",
    image: "/assets/products/last30days.png",
    productPage: {
      tabLabel: "Last30Days",
      category: "Live Signal Intelligence",
      image: {
        src: "/assets/products/last30days-products-og.png",
        alt: "Last30Days product graphic",
        width: 1731,
        height: 909
      },
      sections: [
        {
          label: "What it is",
          paragraphs: [
            "Every business decision made without knowing what the market is saying right now is a guess dressed up as strategy.",
            "Last30Days scrapes Reddit. X. TikTok. Instagram. YouTube and the open web, pulling every conversation from the last thirty days. Ask any question — search a competitor, a trend, a product category, a new release — and get a structured, sourced report in under 60 seconds. Every claim cited."
          ]
        },
        {
          label: "Where markets form their opinions",
          paragraphs: [
            "This is where markets form their opinions. Where trends emerge before they reach the trade press. Where your competitors are being discussed, praised, or quietly abandoned."
          ]
        },
        {
          label: "What it replaces",
          paragraphs: [
            "What used to take a research team, an agency brief, or a six-figure contract is now delivered in one search.",
            "Before you launch, pivot, or compete — know what the market is really saying right now."
          ],
        }
      ],
      ctas: [{ label: "Visit live site →", href: "https://last30days.app", external: true }]
    }
  },
  {
    slug: "fire-source",
    title: "Fire Source",
    eyebrow: "Commercial intelligence / cited web research",
    promise: "Commercial intelligence from the open web.",
    status: "Placeholder case study",
    proofCopy:
      "Fire Source scans ~96% of the open web and answers your commercial questions in three minutes. Stack follow-ups to sharpen the picture and find the angle nobody else has. Competitor moves, market shifts, who's buying what, who's hiring whom, pricing moves, prospect intelligence all in under three minutes. Cited, complete, with prompts to turn the intel into pitches, emails, or strategy notes. Built by Studio Baggio.",
    problem:
      "Commercial teams need competitor moves, market shifts, buyer signals and pitch intelligence faster than manual research allows.",
    built:
      "A research system that scans the open web, answers commercial questions quickly and turns cited intelligence into pitches, emails and strategy notes.",
    whyItMatters:
      "It can turn research into usable artefacts like pitch hooks, cold emails, battle cards, strategy notes and creative briefs.",
    proves:
      "Studio Baggio can build commercial intelligence products that preserve source discipline while accelerating decisions.",
    href: "/fire-source",
    external: "https://fire-source.vercel.app",
    homepageLinks: [{ label: "Visit live site →", href: "https://fire-source.vercel.app" }],
    homepageImage: "/assets/products/fire-source-og.png",
    image: "/assets/products/fire-source.png",
    productPage: {
      tabLabel: "Fire Source",
      category: "Commercial Intelligence",
      image: {
        src: "/assets/products/fire-source-products-og.png",
        alt: "Fire Source product graphic",
        width: 1731,
        height: 909
      },
      sections: [
        {
          label: "Market Intelligence Before The Meeting",
          paragraphs: [
            "Fire Source gives you the intelligence to walk into any client meeting, pitch, or competitive review with an unfair advantage. Research a market, a competitor, or a trend — and get a structured, cited briefing in minutes."
          ]
        },
        {
          label: "What It Replaces",
          paragraphs: [
            "It replaces hours of manual research, briefings that go out of date, agency-commissioned reports, scattered Google searches and competitor benchmarking sessions."
          ]
        },
        {
          label: "Built for Firms That Move Fast",
          paragraphs: [
            "Fire Source is designed for advisory firms, consultancies and product teams who need commercial intelligence before the meeting — not after. Competitors. Market shifts. Prospects. Cited sources."
          ]
        }
      ],
      ctas: [{ label: "Visit live site →", href: "https://fire-source.vercel.app", external: true }]
    }
  }
];
